# Generated by Django 4.0.1 on 2022-03-28 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('word', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(choices=[('noun', 'noun'), ('pronoun', 'pronoun'), ('verb', 'verb'), ('adjective', 'adjective'), ('adverb', 'adverb'), ('preposition', 'preposition'), ('conjunction', 'conjunction'), ('interjection', 'interjection'), ('phrase', 'phrase')], max_length=100)),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('my_sentence', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
