# Generated by Django 4.0.1 on 2022-03-31 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='correct',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'noun'), ('verb', 'verb'), ('adjective', 'adjective'), ('adverb', 'adverb'), ('phrase', 'phrase'), ('conjunction', 'conjunction'), ('preposition', 'preposition'), ('pronoun', 'pronoun'), ('interjection', 'interjection')], max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='wrong',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
