# Generated by Django 4.0.3 on 2022-04-09 14:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_word_correct_alter_word_part_of_speech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('noun', 'noun'), ('verb', 'verb'), ('adjective', 'adjective'), ('adverb', 'adverb'), ('phrase', 'phrase'), ('conjunction', 'conjunction'), ('preposition', 'preposition'), ('pronoun', 'pronoun'), ('interjection', 'interjection')], max_length=78),
        ),
    ]
